<a href="https://colab.research.google.com/github/myfirstgithub0512/Shruti_INFO5731_Spring2020/blob/master/INFO5731_Assignment_Three.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 Assignment Three**

In this assignment, you are required to conduct information extraction, semantic analysis based on **the dataset you collected from assignment two**. You may use scipy and numpy package in this assignment.

# **Question 1: Understand N-gram**

(45 points). Write a python program to conduct N-gram analysis based on the dataset in your assignment two:

(1) Count the frequency of all the N-grams (N=3).

(2) Calculate the probabilities for all the bigrams in the dataset by using the fomular count(w2 w1) / count(w2). For example, count(really like) / count(really) = 1 / 3 = 0.33.

(3) Extract all the **noun phrases** and calculate the relative probabilities of each review in terms of other reviews (abstracts, or tweets) by using the fomular frequency (noun phrase) / max frequency (noun phrase) on the whole dataset. Print out the result in a table with column name the all the noun phrases and row name as all the 100 reviews (abstracts, or tweets). 


In [0]:
#1.1
import nltk
from collections import Counter
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
f = open('/content/f3.txt')
raw = f.read()
#print(raw)
tokens = nltk.word_tokenize(raw)
a = nltk.trigrams(tokens)
fdist = nltk.FreqDist(a) #compute frequency for all the bigrams in the text
for key,value in fdist.items():
   print(key,value)

Streaming output truncated to the last 5000 lines.
('speed', 'pro', 'air') 1
('pro', 'air', 'difference') 1
('air', 'difference', 'notable') 1
('difference', 'notable', 'run') 1
('notable', 'run', 'cpu') 1
('run', 'cpu', 'intensive') 1
('cpu', 'intensive', 'task') 1
('intensive', 'task', 'like') 1
('task', 'like', 'programming') 1
('like', 'programming', 'video') 1
('programming', 'video', 'encoding') 1
('video', 'encoding', 'photo') 1
('encoding', 'photo', 'editing') 1
('photo', 'editing', 'raw') 1
('editing', 'raw', 'conversion') 1
('raw', 'conversion', 'etc') 1
('conversion', 'etc', 'go') 1
('etc', 'go', 'air') 1
('go', 'air', 'save') 1
('air', 'save', 'money') 1
('save', 'money', 'newer') 1
('money', 'newer', 'cpu') 1
('newer', 'cpu', 'macbook') 1
('cpu', 'macbook', 'air') 1
('macbook', 'air', 'evolved') 1
('air', 'evolved', 'much') 1
('evolved', 'much', 'compared') 1
('much', 'compared', 'pro') 1
('compared', 'pro', 'air') 1
('pro', 'air', 'us') 1
('air', 'us', 'fifth') 1
('us', '

In [0]:
#1.2
import re
import string
f = open("/content/f3.txt", "r")
rawtext = f.read()
bigrams = {}
words_punct = rawtext.split()
words = [ w. strip(string.punctuation).lower() for w in words_punct ]
words = ["START"] + words + ["END"]
for index, word in enumerate(words):
    if index < len(words) - 1:
     w1 = words[index ] 
     w2 = words[index + 1]
    bigram = (w1, w2) # really like
    if bigram in bigrams:
        bigrams[ bigram ] = bigrams[ bigram ] + 1
    else:
        bigrams[ bigram ] = 1

sorted_bigrams = sorted(bigrams.items(), key = lambda pair:pair[0], reverse = True)
for bigram, count in sorted_bigrams:
    Bi_Prob = count / sum(list(bigrams.values()))
    print(bigram, Bi_Prob)



Streaming output truncated to the last 5000 lines.
('three', 'month') 0.0004516031913292187
('thousand', 'time') 0.0001505343971097396
('thousand', 'repair') 0.0001505343971097396
('thousand', 'get') 0.0001505343971097396
('thousand', 'apple') 0.0001505343971097396
('thought', 'service') 0.0001505343971097396
('thought', 'dirt') 0.0001505343971097396
('though', 'window') 0.0001505343971097396
('though', 'spacebar') 0.0001505343971097396
('though', 'resolution') 0.0001505343971097396
('though', 'love') 0.0001505343971097396
('though', 'graphic') 0.0001505343971097396
('though', 'get') 0.0001505343971097396
('though', 'bad') 0.0001505343971097396
('thisupdate', 'oct') 0.0001505343971097396
('thisi', 'update') 0.0001505343971097396
('third', 'party') 0.0001505343971097396
('thinking', 'buying') 0.0001505343971097396
('think', 'thousand') 0.0001505343971097396
('think', 'reconsider') 0.0001505343971097396
('think', 'plight') 0.0001505343971097396
('think', 'older') 0.0001505343971097396
('

In [0]:
#1.3
import nltk
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
nltk.download("brown")
nltk.download('punkt')
import spacy
from textblob import TextBlob

# Extracting all noun phrases
nlp = spacy.load("en")
text = open ("f3.txt","r")
doc = nlp(text.read())
#print(file)
#blob = TextBlob(file)
#print(blob.noun_phrases)
noun = []
for sentence in doc.noun_chunks:
  noun.append(sentence.text)
df = pd.DataFrame(noun, columns=['noun'])
cvec = CountVectorizer(analyzer="word", ngram_range=(2,2))
sf = cvec.fit_transform(df['noun'].values.astype("U"))
freq =sum(sf).toarray()[0]
df = pd.DataFrame (freq,index = cvec.get_feature_names(),columns=["frequency"])
df["nounprobabilities"] =df/df.max()
df.head(100)

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


frequency  nounprobabilities
abit reluctant               1           0.038462
abovea mac                   1           0.038462
accidental fall              1           0.038462
accounting software          1           0.038462
activity mac                 1           0.038462
...                        ...                ...
apple applemy                1           0.038462
apple approval               1           0.038462
apple authorized             1           0.038462
apple battery                1           0.038462
apple care                   1           0.038462

[100 rows x 2 columns]

# **Question 2: Undersand TF-IDF and Document representation**

(40 points). Starting from the documents (all the reviews, or abstracts, or tweets) collected for assignment two, write a python program: 

(1) To build the **documents-terms weights (tf*idf) matrix bold text**.

(2) To rank the documents with respect to query (design a query by yourself, for example, "An Outstanding movie with a haunting performance and best character development") by using **cosine similarity**.

In [0]:
#2.1
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer

documents = list()
with open("/content/f3.txt") as file:
    for line in file:
        for l in re.split(r"\.\s|\?\s|\!\s|\n",line):
            if l:
               documents.append(l)

document_names = ['Doc {:d}'.format(i) for i in range (len (documents))]

def get_tfidf(documents, ngram_range=(0,1), index=None):
  #cvec = CountVectorizer(stop_words='english', min_df=3, max_df=0.5, ngram_range=(1,2))
    vect = TfidfVectorizer(stop_words='english',max_features=10, ngram_range=(1,2),min_df= 3, max_df= 0.8)
    tfidf = vect.fit_transform(documents).todense()
    return pd.DataFrame(tfidf, columns=vect.get_feature_names(), index=index).T

print(get_tfidf(documents, ngram_range=(1,2), index = document_names))

      

         Doc 0     Doc 1     Doc 2  Doc 3  ...  Doc 287  Doc 288   Doc 289  Doc 290
air        0.0  0.000000  0.223274    0.0  ...      0.0      0.0  0.000000      0.0
amazon     0.0  0.000000  0.000000    1.0  ...      0.0      0.0  0.000000      0.0
apple      0.0  0.359177  0.158275    0.0  ...      0.0      0.0  0.769132      0.0
battery    0.0  0.000000  0.378556    0.0  ...      0.0      0.0  0.000000      0.0
good       0.0  0.323410  0.142515    0.0  ...      1.0      1.0  0.000000      0.0
laptop     0.0  0.000000  0.782615    0.0  ...      0.0      0.0  0.000000      0.0
mac        0.0  0.000000  0.216633    0.0  ...      0.0      0.0  0.000000      0.0
macbook    0.0  0.822998  0.181332    0.0  ...      0.0      0.0  0.000000      0.0
product    0.0  0.298449  0.263030    0.0  ...      0.0      0.0  0.639090      0.0
window     0.0  0.000000  0.000000    0.0  ...      0.0      0.0  0.000000      0.0

[10 rows x 291 columns]


In [0]:
#2.2
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk.corpus import stopwords
import numpy as np
import numpy.linalg as LA
from array import array
nltk.download('stopwords')
from nltk.corpus import stopwords


query_set=["best laptop."]
stopWords = stopwords.words('english')


documents = list()
with open("//content/Demo1.csv") as file:
  for line in file:
    for l in re.split(r"\.\s|\?\s|\!\s|\n",line):
      if l:
        documents.append(l)

vectorizer = CountVectorizer(stop_words = stopWords)
transformer = TfidfTransformer()

trainVectorizerArray = vectorizer.fit_transform(documents).toarray()
testVectorizerArray = vectorizer.transform(query_set).toarray()
print('Fit Vectorizer to train set', trainVectorizerArray)
print('Transform Vectorizer to test set', testVectorizerArray)

cx = lambda a, b : round(np.inner(a, b)/(LA.norm(a)*LA.norm(b)), 3)

for vector in trainVectorizerArray:
 #   print(vector)
    for testV in testVectorizerArray:
 #       print(testV)
        cosine = cx(vector, testV)
        print(cosine)





[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Fit Vectorizer to train set [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Transform Vectorizer to test set [[0 0 0 ... 0 0 0]]
0.0
0.0
0.35
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.079
0.236
0.088
0.0
0.197
0.213
0.137
0.0
0.0
0.115
0.0
0.133
0.083
0.136
0.094
0.0
0.0
0.0
0.289
0.0
0.099
0.092
0.25
0.0
0.2
0.0
0.0
0.109
0.0
0.0
0.104
0.279
0.0
0.069
0.198
0.082
0.07
0.0
0.086
0.0
0.0
0.289
0.0
0.0
0.0
0.099
0.0
0.0
0.141
0.408
0.1
0.0
0.0
0.0
0.283
0.213
0.0
0.226
0.394
0.254
0.146
0.0
0.141
0.0
0.156
0.083
0.0
0.121
0.0
0.0
0.263
0.0
0.0
0.0
0.0
0.0
0.154
0.0
0.0
0.0
0.229
0.091
0.101
0.162
0.067
0.0
0.0
0.123
0.076
0.0
0.147
0.0
0.236
0.167
0.2
0.485
0.331
0.0
0.116
0.204
0.136
0.0
0.254
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.159
0.318
0.136
0.115
0.0
0.0
0.0
0.0
0.0
0.0
0.267
0.0
0.0
0.378
0.196
0.0
0.0
0

# **Question 3: Create your own training and evaluation data for sentiment analysis**

(15 points). **You dodn't need to write program for this question!** Read each review (abstract or tweet) you collected in detail, and annotate each review with a sentiment (positive, negative, or neutral). Save the annotated dataset into a csv file with three columns (first column: document_id, clean_text, sentiment), upload the csv file to GitHub and submit the file link blew. This datset will be used for assignment four: sentiment analysis and text classification. 


In [0]:
# The GitHub link of your final csv file

# Link: https://github.com/myfirstgithub0512/Shruti_INFO5731_Spring2020/blob/master/Shruti_reviews_sentiments.csv